name=input("Please input your name " )
age=int(input("Please input your age "))
m1=int(input("Please input your marks 1 "))
m2=int(input("Please input your marks 2 "))
m3=int(input("Please input your marks 3 "))
m4=int(input("Please input your marks 4 "))
m5=int(input("Please input your marks 5 "))
sum=m1+m2+m3+m4+m5
ava=sum/5
print()
print("*********************")
print("Student marks sheet")
print("*********************")
print("Student name : ",name)
print("Student age : ",age)
print("Marks 1 : ",m1)
print("Marks 2 : ",m2)
print("Marks 3 : ",m3)
print("Marks 4 : ",m4)
print("Marks 5 : ",m5)
print("Sum = ",sum)
print("avarage = ",ava)
print("*********************")
